export const data = [
  { num: 1, bg: "#FF0000", numString: "one", dozen: '1', col: '1', oddOrEven: "odd", color: "red", range: "1-18"  ,ssRange:"1-3" ,dsRange:"1-6"},
  { num: 2, bg: "black", numString: "two", dozen: '1', col: '2', oddOrEven: "even", color: "black", range: "1-18" ,ssRange:"1-3" ,dsRange:"1-6"},
  { num: 3, bg: "#FF0000", numString: "three", dozen: '1', col: '3', oddOrEven: "odd", color: "red", range: "1-18" ,ssRange:"1-3" ,dsRange:"1-6"},
  { num: 4, bg: "black", numString: "four", dozen: '1', col: '1', oddOrEven: "even", color: "black", range: "1-18" ,ssRange:"4-6" ,dsRange:"1-6"},
  { num: 5, bg: "#FF0000", numString: "five", dozen: '1', col: '2', oddOrEven: "odd", color: "red", range: "1-18" ,ssRange:"4-6" ,dsRange:"1-6"},
  { num: 6, bg: "black", numString: "six", dozen: '1', col: '3', oddOrEven: "even", color: "black", range: "1-18" ,ssRange:"4-6" ,dsRange:"1-6"},
  { num: 7, bg: "#FF0000", numString: "seven", dozen: '1', col: '1', oddOrEven: "odd", color: "red", range: "1-18" ,ssRange:"7-9" ,dsRange:"7-12"},
  { num: 8, bg: "black", numString: "eight", dozen: '1', col: '2', oddOrEven: "even", color: "black", range: "1-18" ,ssRange:"7-9" ,dsRange:"7-12"},
  { num: 9, bg: "#FF0000", numString: "nine", dozen: '1', col: '3', oddOrEven: "odd", color: "red", range: "1-18" ,ssRange:"7-9" ,dsRange:"7-12"},
  { num: 10, bg: "black", numString: "ten", dozen: '1', col: '1', oddOrEven: "even", color: "black", range: "1-18" ,ssRange:"10-12" ,dsRange:"7-12"},
  { num: 11, bg: "black", numString: "eleven", dozen: '1', col: '2', oddOrEven: "odd", color: "black", range: "1-18" ,ssRange:"10-12" ,dsRange:"7-12"},
  { num: 12, bg: "#FF0000", numString: "twelve", dozen: '1', col: '3', oddOrEven: "even", color: "red", range: "1-18" ,ssRange:"10-12" ,dsRange:"7-12"},
  { num: 13, bg: "black", numString: "thirteen", dozen: '2', col: '1', oddOrEven: "odd", color: "black", range: "1-18" ,ssRange:"13-15" ,dsRange:"13-18"},
  { num: 14, bg: "#FF0000", numString: "fourteen", dozen: '2', col: '2', oddOrEven: "even", color: "red", range: "1-18" ,ssRange:"13-15" ,dsRange:"13-18"},
  { num: 15, bg: "black", numString: "fifteen", dozen: '2', col: '3', oddOrEven: "odd", color: "black", range: "1-18" ,ssRange:"13-15" ,dsRange:"13-18"},
  { num: 16, bg: "#FF0000", numString: "sixteen", dozen: '2', col: '1', oddOrEven: "even", color: "red", range: "1-18" ,ssRange:"16-18" ,dsRange:"13-18"},
  { num: 17, bg: "black", numString: "seventeen", dozen: '2', col: '2', oddOrEven: "odd", color: "black", range: "1-18" ,ssRange:"16-18" ,dsRange:"13-18"},
  { num: 18, bg: "#FF0000", numString: "eighteen", dozen: '2', col: '3', oddOrEven: "even", color: "red", range: "1-18" ,ssRange:"16-18" ,dsRange:"13-18"},
  { num: 19, bg: "#FF0000", numString: "nineteen", dozen: '2', col: '1', oddOrEven: "odd", color: "red", range: "19-36" ,ssRange:"19-21" ,dsRange:"19-24"},
  { num: 20, bg: "black", numString: "twenty", dozen: '2', col: '2', oddOrEven: "even", color: "black", range: "19-36" ,ssRange:"19-21" ,dsRange:"19-24"},
  { num: 21, bg: "#FF0000", numString: "twentyOne", dozen: '2', col: '3', oddOrEven: "odd", color: "red", range: "19-36" ,ssRange:"19-21" ,dsRange:"19-24"},
  { num: 22, bg: "black", numString: "twentyTwo", dozen: '2', col: '1', oddOrEven: "even", color: "black", range: "19-36" ,ssRange:"22-24" ,dsRange:"19-24"},
  { num: 23, bg: "#FF0000", numString: "twentyThree", dozen: '2', col: '2', oddOrEven: "odd", color: "red", range: "19-36" ,ssRange:"22-24" ,dsRange:"19-24"},
  { num: 24, bg: "black", numString: "twentyFour", dozen: '2', col: '3', oddOrEven: "even", color: "black", range: "19-36" ,ssRange:"22-24" ,dsRange:"19-24"},
  { num: 25, bg: "#FF0000", numString: "twentyFive", dozen: '3', col: '1', oddOrEven: "odd", color: "red", range: "19-36" ,ssRange:"25-27" ,dsRange:"25-30"},
  { num: 26, bg: "black", numString: "twentySix", dozen: '3', col: '2', oddOrEven: "even", color: "black", range: "19-36" ,ssRange:"25-27" ,dsRange:"25-30"},
  { num: 27, bg: "#FF0000", numString: "twentySeven", dozen: '3', col: '3', oddOrEven: "odd", color: "red", range: "19-36" ,ssRange:"25-27" ,dsRange:"25-30"},
  { num: 28, bg: "black", numString: "twentyEight", dozen: '3', col: '1', oddOrEven: "even", color: "black", range: "19-36" ,ssRange:"28-30" ,dsRange:"25-30"},
  { num: 29, bg: "black", numString: "twentyNine", dozen: '3', col: '2', oddOrEven: "odd", color: "black", range: "19-36" ,ssRange:"28-30" ,dsRange:"25-30"},
  { num: 30, bg: "#FF0000", numString: "thirty", dozen: '3', col: '3', oddOrEven: "even", color: "red", range: "19-36" ,ssRange:"28-30" ,dsRange:"25-30"},
  { num: 31, bg: "black", numString: "thirtyOne", dozen: '3', col: '1', oddOrEven: "odd", color: "black", range: "19-36" ,ssRange:"31-33" ,dsRange:"31-36"},
  { num: 32, bg: "#FF0000", numString: "thirtyTwo", dozen: '3', col: '2', oddOrEven: "even", color: "red", range: "19-36" ,ssRange:"31-33" ,dsRange:"31-36"},
  { num: 33, bg: "black", numString: "thirtyThree", dozen: '3', col: '3', oddOrEven: "odd", color: "black", range: "19-36" ,ssRange:"31-33" ,dsRange:"31-36"},
  { num: 34, bg: "#FF0000", numString: "thirtyFour", dozen: '3', col: '1', oddOrEven: "even", color: "red", range: "19-36" ,ssRange:"34-36" ,dsRange:"31-36"},
  { num: 35, bg: "black", numString: "thirtyFive", dozen: '3', col: '2', oddOrEven: "odd", color: "black", range: "19-36" ,ssRange:"34-36" ,dsRange:"31-36"},
  { num: 36, bg: "#FF0000", numString: "thirtySix", dozen: '3', col: '3', oddOrEven: "even", color: "red", range: "19-36" ,ssRange:"34-36" ,dsRange:"31-36"},
];

// export const data = [
//   { num: 1, bg: "#FF0000", numString: "one", dozen: '1', col: '1', oddOrEven: "odd", color: "red", range: "1-18" },
//   { num: 2, bg: "black", numString: "two", dozen: '1', col: '2', oddOrEven: "even", color: "black", range: "1-18" },
//   { num: 3, bg: "#FF0000", numString: "three", dozen: '1', col: '3', oddOrEven: "odd", color: "red", range: "1-18" },
//   { num: 4, bg: "black", numString: "four", dozen: '1', col: '1', oddOrEven: "even", color: "black", range: "1-18" },
//   { num: 5, bg: "#FF0000", numString: "five", dozen: '1', col: '2', oddOrEven: "odd", color: "red", range: "1-18" },
//   { num: 6, bg: "black", numString: "six", dozen: '1', col: '3', oddOrEven: "even", color: "black", range: "1-18" },
//   { num: 7, bg: "#FF0000", numString: "seven", dozen: '1', col: '1', oddOrEven: "odd", color: "red", range: "1-18" },
//   { num: 8, bg: "black", numString: "eight", dozen: '1', col: '2', oddOrEven: "even", color: "black", range: "1-18" },
//   { num: 9, bg: "#FF0000", numString: "nine", dozen: '1', col: '3', oddOrEven: "odd", color: "red", range: "1-18" },
//   { num: 10, bg: "black", numString: "ten", dozen: '1', col: '1', oddOrEven: "even", color: "black", range: "1-18" },
//   { num: 11, bg: "black", numString: "eleven", dozen: '1', col: '2', oddOrEven: "odd", color: "black", range: "1-18" },
//   { num: 12, bg: "#FF0000", numString: "twelve", dozen: '1', col: '3', oddOrEven: "even", color: "red", range: "1-18" },
//   { num: 13, bg: "black", numString: "thirteen", dozen: '2', col: '1', oddOrEven: "odd", color: "black", range: "1-18" },
//   { num: 14, bg: "#FF0000", numString: "fourteen", dozen: '2', col: '2', oddOrEven: "even", color: "red", range: "1-18" },
//   { num: 15, bg: "black", numString: "fifteen", dozen: '2', col: '3', oddOrEven: "odd", color: "black", range: "1-18" },
//   { num: 16, bg: "#FF0000", numString: "sixteen", dozen: '2', col: '1', oddOrEven: "even", color: "red", range: "1-18" },
//   { num: 17, bg: "black", numString: "seventeen", dozen: '2', col: '2', oddOrEven: "odd", color: "black", range: "1-18" },
//   { num: 18, bg: "#FF0000", numString: "eighteen", dozen: '2', col: '3', oddOrEven: "even", color: "red", range: "1-18" },
//   { num: 19, bg: "#FF0000", numString: "nineteen", dozen: '2', col: '1', oddOrEven: "odd", color: "red", range: "19-36" },
//   { num: 20, bg: "black", numString: "twenty", dozen: '2', col: '2', oddOrEven: "even", color: "black", range: "19-36" },
//   { num: 21, bg: "#FF0000", numString: "twentyOne", dozen: '2', col: '3', oddOrEven: "odd", color: "red", range: "19-36" },
//   { num: 22, bg: "black", numString: "twentyTwo", dozen: '2', col: '1', oddOrEven: "even", color: "black", range: "19-36" },
//   { num: 23, bg: "#FF0000", numString: "twentyThree", dozen: '2', col: '2', oddOrEven: "odd", color: "red", range: "19-36" },
//   { num: 24, bg: "black", numString: "twentyFour", dozen: '2', col: '3', oddOrEven: "even", color: "black", range: "19-36" },
//   { num: 25, bg: "#FF0000", numString: "twentyFive", dozen: '3', col: '1', oddOrEven: "odd", color: "red", range: "19-36" },
//   { num: 26, bg: "black", numString: "twentySix", dozen: '3', col: '2', oddOrEven: "even", color: "black", range: "19-36" },
//   { num: 27, bg: "#FF0000", numString: "twentySeven", dozen: '3', col: '3', oddOrEven: "odd", color: "red", range: "19-36" },
//   { num: 28, bg: "black", numString: "twentyEight", dozen: '3', col: '1', oddOrEven: "even", color: "black", range: "19-36" },
//   { num: 29, bg: "black", numString: "twentyNine", dozen: '3', col: '2', oddOrEven: "odd", color: "black", range: "19-36" },
//   { num: 30, bg: "#FF0000", numString: "thirty", dozen: '3', col: '3', oddOrEven: "even", color: "red", range: "19-36" },
//   { num: 31, bg: "black", numString: "thirtyOne", dozen: '3', col: '1', oddOrEven: "odd", color: "black", range: "19-36" },
//   { num: 32, bg: "#FF0000", numString: "thirtyTwo", dozen: '3', col: '2', oddOrEven: "even", color: "red", range: "19-36" },
//   { num: 33, bg: "black", numString: "thirtyThree", dozen: '3', col: '3', oddOrEven: "odd", color: "black", range: "19-36" },
//   { num: 34, bg: "#FF0000", numString: "thirtyFour", dozen: '3', col: '1', oddOrEven: "even", color: "red", range: "19-36" },
//   { num: 35, bg: "black", numString: "thirtyFive", dozen: '3', col: '2', oddOrEven: "odd", color: "black", range: "19-36" },
//   { num: 36, bg: "#FF0000", numString: "thirtySix", dozen: '3', col: '3', oddOrEven: "even", color: "red", range: "19-36" },
// ];





// export const data = [
//   //   { num: 0, bg: "##06D001", numString: "zero" },
//   //   { num: "00", bg: "#06D001", numString: "doubleZero" },
//   { num: 1, bg: "#FF0000", numString: "one" },
//   { num: 2, bg: "black", numString: "two" },
//   { num: 3, bg: "#FF0000", numString: "three" },
//   { num: 4, bg: "black", numString: "four" },
//   { num: 5, bg: "#FF0000", numString: "five" },
//   { num: 6, bg: "black", numString: "six" },
//   { num: 7, bg: "#FF0000", numString: "seven" },
//   { num: 8, bg: "black", numString: "eight" },
//   { num: 9, bg: "#FF0000", numString: "nine" },
//   { num: 10, bg: "black", numString: "ten" },
//   { num: 11, bg: "black", numString: "eleven" },
//   { num: 12, bg: "#FF0000", numString: "twelve" },
//   { num: 13, bg: "black", numString: "thirteen" },
//   { num: 14, bg: "#FF0000", numString: "fourteen" },
//   { num: 15, bg: "black", numString: "fifteen" },
//   { num: 16, bg: "#FF0000", numString: "sixteen" },
//   { num: 17, bg: "black", numString: "seventeen" },
//   { num: 18, bg: "#FF0000", numString: "eighteen" },
//   { num: 19, bg: "#FF0000", numString: "nineteen" },
//   { num: 20, bg: "black", numString: "twenty" },
//   { num: 21, bg: "#FF0000", numString: "twentyOne" },
//   { num: 22, bg: "black", numString: "twentyTwo" },
//   { num: 23, bg: "#FF0000", numString: "twentyThree" },
//   { num: 24, bg: "black", numString: "twentyFour" },
//   { num: 25, bg: "#FF0000", numString: "twentyFive" },
//   { num: 26, bg: "black", numString: "twentySix" },
//   { num: 27, bg: "#FF0000", numString: "twentySeven" },
//   { num: 28, bg: "black", numString: "twentyEight" },
//   { num: 29, bg: "black", numString: "twentyNine" },
//   { num: 30, bg: "#FF0000", numString: "thirty" },
//   { num: 31, bg: "black", numString: "thirtyOne" },
//   { num: 32, bg: "#FF0000", numString: "thirtyTwo" },
//   { num: 33, bg: "black", numString: "thirtyThree" },
//   { num: 34, bg: "#FF0000", numString: "thirtyFour" },
//   { num: 35, bg: "black", numString: "thirtyFive" },
//   { num: 36, bg: "#FF0000", numString: "thirtySix" },
// ];
