export const data = [
  //   { num: 0, bg: "##06D001", numString: "zero" },
  //   { num: "00", bg: "#06D001", numString: "doubleZero" },
  { num: 1, bg: "#FF0000", numString: "one" },
  { num: 2, bg: "black", numString: "two" },
  { num: 3, bg: "#FF0000", numString: "three" },
  { num: 4, bg: "black", numString: "four" },
  { num: 5, bg: "#FF0000", numString: "five" },
  { num: 6, bg: "black", numString: "six" },
  { num: 7, bg: "#FF0000", numString: "seven" },
  { num: 8, bg: "black", numString: "eight" },
  { num: 9, bg: "#FF0000", numString: "nine" },
  { num: 10, bg: "black", numString: "ten" },
  { num: 11, bg: "black", numString: "eleven" },
  { num: 12, bg: "#FF0000", numString: "twelve" },
  { num: 13, bg: "black", numString: "thirteen" },
  { num: 14, bg: "#FF0000", numString: "fourteen" },
  { num: 15, bg: "black", numString: "fifteen" },
  { num: 16, bg: "#FF0000", numString: "sixteen" },
  { num: 17, bg: "black", numString: "seventeen" },
  { num: 18, bg: "#FF0000", numString: "eighteen" },
  { num: 19, bg: "#FF0000", numString: "nineteen" },
  { num: 20, bg: "black", numString: "twenty" },
  { num: 21, bg: "#FF0000", numString: "twentyOne" },
  { num: 22, bg: "black", numString: "twentyTwo" },
  { num: 23, bg: "#FF0000", numString: "twentyThree" },
  { num: 24, bg: "black", numString: "twentyFour" },
  { num: 25, bg: "#FF0000", numString: "twentyFive" },
  { num: 26, bg: "black", numString: "twentySix" },
  { num: 27, bg: "#FF0000", numString: "twentySeven" },
  { num: 28, bg: "black", numString: "twentyEight" },
  { num: 29, bg: "black", numString: "twentyNine" },
  { num: 30, bg: "#FF0000", numString: "thirty" },
  { num: 31, bg: "black", numString: "thirtyOne" },
  { num: 32, bg: "#FF0000", numString: "thirtyTwo" },
  { num: 33, bg: "black", numString: "thirtyThree" },
  { num: 34, bg: "#FF0000", numString: "thirtyFour" },
  { num: 35, bg: "black", numString: "thirtyFive" },
  { num: 36, bg: "#FF0000", numString: "thirtySix" },
];
