
// new 9 number logic data

// export const data = [
//   //   { num: 0, bg: "##06D001", numString: "zero" },
//   //   { num: "00", bg: "#06D001", numString: "doubleZero" },
//   { num: 1, bg: "#FF0000", numString: "one", letter : 'C', dozen : '1', col : '1' },
//   { num: 2, bg: "black", numString: "two", letter : 'A', dozen : '1', col : '2' },
//   { num: 3, bg: "#FF0000", numString: "three", letter : 'D', dozen : '1', col : '3' },
//   { num: 4, bg: "black", numString: "four", letter : 'A', dozen : '1', col : '1' },
//   { num: 5, bg: "#FF0000", numString: "five", letter : 'C', dozen : '1', col : '2' },
//   { num: 6, bg: "black", numString: "six", letter : 'B', dozen : '1', col : '3' },
//   { num: 7, bg: "#FF0000", numString: "seven", letter : 'D', dozen : '1', col : '1' },
//   { num: 8, bg: "black", numString: "eight", letter : 'B', dozen : '1', col : '2' },
//   { num: 9, bg: "#FF0000", numString: "nine", letter : 'C', dozen : '1', col : '3' },
//   { num: 10, bg: "black", numString: "ten", letter : 'B', dozen : '1', col : '1' },
//   { num: 11, bg: "black", numString: "eleven", letter : 'B', dozen : '1', col : '2' },
//   { num: 12, bg: "#FF0000", numString: "twelve", letter : 'D', dozen : '1', col : '3' },
//   { num: 13, bg: "black", numString: "thirteen", letter : 'B', dozen : '2', col : '1' },
//   { num: 14, bg: "#FF0000", numString: "fourteen", letter : 'C', dozen : '2', col : '2' },
//   { num: 15, bg: "black", numString: "fifteen", letter : 'A', dozen : '2', col : '3' },
//   { num: 16, bg: "#FF0000", numString: "sixteen", letter : 'C', dozen : '2', col : '1' },
//   { num: 17, bg: "black", numString: "seventeen", letter : 'A', dozen : '2', col : '2' },
//   { num: 18, bg: "#FF0000", numString: "eighteen", letter : 'D', dozen : '2', col : '3' },
//   { num: 19, bg: "#FF0000", numString: "nineteen", letter : 'A', dozen : '2', col : '1' },
//   { num: 20, bg: "black", numString: "twenty", letter : 'C', dozen : '2', col : '2' },
//   { num: 21, bg: "#FF0000", numString: "twentyOne", letter : 'A', dozen : '2', col : '3' },
//   { num: 22, bg: "black", numString: "twentyTwo", letter : 'D', dozen : '2', col : '1' },
//   { num: 23, bg: "#FF0000", numString: "twentyThree", letter : 'B', dozen : '2', col : '2' },
//   { num: 24, bg: "black", numString: "twentyFour", letter : 'C', dozen : '2', col : '3' },
//   { num: 25, bg: "#FF0000", numString: "twentyFive", letter : 'A', dozen : '3', col : '1' },
//   { num: 26, bg: "black", numString: "twentySix", letter : 'D', dozen : '3', col : '2' },
//   { num: 27, bg: "#FF0000", numString: "twentySeven", letter : 'B', dozen : '3', col : '3' },
//   { num: 28, bg: "black", numString: "twentyEight", letter : 'D', dozen : '3', col : '1' },
//   { num: 29, bg: "black", numString: "twentyNine", letter : 'D', dozen : '3', col : '2' },
//   { num: 30, bg: "#FF0000", numString: "thirty", letter : 'B', dozen : '3', col : '3' },
//   { num: 31, bg: "black", numString: "thirtyOne", letter : 'C', dozen : '3', col : '1' },
//   { num: 32, bg: "#FF0000", numString: "thirtyTwo", letter : 'A', dozen : '3', col : '2' },
//   { num: 33, bg: "black", numString: "thirtyThree", letter : 'C', dozen : '3', col : '3' },
//   { num: 34, bg: "#FF0000", numString: "thirtyFour", letter : 'A', dozen : '3', col : '1' },
//   { num: 35, bg: "black", numString: "thirtyFive", letter : 'D', dozen : '3', col : '2' },
//   { num: 36, bg: "#FF0000", numString: "thirtySix", letter : 'B', dozen : '3', col : '3' },
// ];



export const data = [
  //   { num: 0, bg: "##06D001", numString: "zero" },
  //   { num: "00", bg: "#06D001", numString: "doubleZero" },
  { num: 1, bg: "#FF0000", numString: "one", letter : 'B', dozen : '1', col : '1' },
  { num: 2, bg: "black", numString: "two", letter : 'A', dozen : '1', col : '2' },
  { num: 3, bg: "#FF0000", numString: "three", letter : 'C', dozen : '1', col : '3' },
  { num: 4, bg: "black", numString: "four", letter : 'A', dozen : '1', col : '1' },
  { num: 5, bg: "#FF0000", numString: "five", letter : 'B', dozen : '1', col : '2' },
  { num: 6, bg: "black", numString: "six", letter : 'A', dozen : '1', col : '3' },
  { num: 7, bg: "#FF0000", numString: "seven", letter : 'C', dozen : '1', col : '1' },
  { num: 8, bg: "black", numString: "eight", letter : 'B', dozen : '1', col : '2' },
  { num: 9, bg: "#FF0000", numString: "nine", letter : 'C', dozen : '1', col : '3' },
  { num: 10, bg: "black", numString: "ten", letter : 'B', dozen : '1', col : '1' },
  { num: 11, bg: "black", numString: "eleven", letter : 'B', dozen : '1', col : '2' },
  { num: 12, bg: "#FF0000", numString: "twelve", letter : 'C', dozen : '1', col : '3' },
  { num: 13, bg: "black", numString: "thirteen", letter : 'A', dozen : '2', col : '1' },
  { num: 14, bg: "#FF0000", numString: "fourteen", letter : 'C', dozen : '2', col : '2' },
  { num: 15, bg: "black", numString: "fifteen", letter : 'A', dozen : '2', col : '3' },
  { num: 16, bg: "#FF0000", numString: "sixteen", letter : 'B', dozen : '2', col : '1' },
  { num: 17, bg: "black", numString: "seventeen", letter : 'A', dozen : '2', col : '2' },
  { num: 18, bg: "#FF0000", numString: "eighteen", letter : 'C', dozen : '2', col : '3' },
  { num: 19, bg: "#FF0000", numString: "nineteen", letter : 'A', dozen : '2', col : '1' },
  { num: 20, bg: "black", numString: "twenty", letter : 'B', dozen : '2', col : '2' },
  { num: 21, bg: "#FF0000", numString: "twentyOne", letter : 'A', dozen : '2', col : '3' },
  { num: 22, bg: "black", numString: "twentyTwo", letter : 'C', dozen : '2', col : '1' },
  { num: 23, bg: "#FF0000", numString: "twentyThree", letter : 'B', dozen : '2', col : '2' },
  { num: 24, bg: "black", numString: "twentyFour", letter : 'B', dozen : '2', col : '3' },
  { num: 25, bg: "#FF0000", numString: "twentyFive", letter : 'A', dozen : '3', col : '1' },
  { num: 26, bg: "black", numString: "twentySix", letter : 'C', dozen : '3', col : '2' },
  { num: 27, bg: "#FF0000", numString: "twentySeven", letter : 'A', dozen : '3', col : '3' },
  { num: 28, bg: "black", numString: "twentyEight", letter : 'C', dozen : '3', col : '1' },
  { num: 29, bg: "black", numString: "twentyNine", letter : 'C', dozen : '3', col : '2' },
  { num: 30, bg: "#FF0000", numString: "thirty", letter : 'B', dozen : '3', col : '3' },
  { num: 31, bg: "black", numString: "thirtyOne", letter : 'C', dozen : '3', col : '1' },
  { num: 32, bg: "#FF0000", numString: "thirtyTwo", letter : 'A', dozen : '3', col : '2' },
  { num: 33, bg: "black", numString: "thirtyThree", letter : 'B', dozen : '3', col : '3' },
  { num: 34, bg: "#FF0000", numString: "thirtyFour", letter : 'A', dozen : '3', col : '1' },
  { num: 35, bg: "black", numString: "thirtyFive", letter : 'C', dozen : '3', col : '2' },
  { num: 36, bg: "#FF0000", numString: "thirtySix", letter : 'B', dozen : '3', col : '3' },
];
